<?php

return array(
  'activityical_group_id' => array(
    'group_name' => 'Activityical Settings',
    'group' => 'activityical',
    'name' => 'activityical_group_id',
    'type' => 'Int',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Only members of this CiviCRM group will have an activity iCalendar feed.',
    'title' =>  'Activity iCalendar Feed Group',
    'help_text' => '',
    'html_type' => 'Select',
    'html_attributes' => array(
      'size' => 10,
      'class' => 'crm-form-multiselect activityical-settings-select',
    ),
    'quick_form_type' => 'Element',
    'X_options_callback' => 'CRM_Activityical_Form_Settings::getGroupOptions',
  ),
  'activityical_activity_type_ids' => array(
    'group_name' => 'Activityical Settings',
    'group' => 'activityical',
    'name' => 'activityical_activity_type_ids',
    'type' => 'Int',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Select one more more options to limit the feed to the selected activity type(s); or select none to skip this limitation. (Use Ctrl+click to select or unselect multiple options.)',
    'title' =>  'Limit by Activity Type',
    'help_text' => '',
    'html_type' => 'Select',
    'html_attributes' => array(
      'multiple' => TRIE,
      'size' => 10,
      'class' => 'crm-form-multiselect activityical-settings-select',
    ),
    'quick_form_type' => 'Element',
    'X_options_callback' => 'CRM_Activityical_Form_Settings::getActivityTypeOptions',
  ),
  'activityical_description_append_targets' => array(
    'group_name' => 'Activityical Settings',
    'group' => 'activityical',
    'name' => 'activityical_description_append_targets',
    'type' => 'Boolean',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Append "with" contacts to Description?',
    'title' =>  'Description includes "with"',
    'help_text' => '',
    'html_type' => 'CheckBox',
    'quick_form_type' => 'Element',
  ),
  'activityical_description_append_assignees' => array(
    'group_name' => 'Activityical Settings',
    'group' => 'activityical',
    'name' => 'activityical_description_append_assignees',
    'type' => 'Boolean',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Append other assigned contacts to Description?',
    'title' =>  'Description includes assignees',
    'help_text' => '',
    'html_type' => 'CheckBox',
    'quick_form_type' => 'Element',
  ),
  'activityical_max_age_days' => array(
    'group_name' => 'Activityical Settings',
    'group' => 'activityical',
    'name' => 'activityical_max_age_days',
    'type' => 'Int',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Maximum number of days in the past, before which no activities will be included in the feed.',
    'title' =>  'Max activity age in days',
    'help_text' => '',
    'html_type' => 'Text',
    'quick_form_type' => 'Element',
    'default' => 30,
    'validate_callback' => 'CRM_Utils_Rule::integer',
    'X_form_rule_args' => array('The field "Max activity age in days" must be an integer', 'integer'),
  ),
 );